
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
  fixme:
    enabled: true
  radon:
    enabled: true
    config: 
      python_version: 3
  pep8:
    enabled: true
  git-legal:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
  - tests/
  - docs/
  - build/
  - dist/
  
