language: python
python:
  - '3.5'
  - '3.6'
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O anaconda.sh;
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda -y
  - conda create -q --name=phynix-env python=$TRAVIS_PYTHON_VERSION
  - source activate phynix-env

install:
# for coverage report
  - pip install coverage
  - pip install coveralls

  - pip install -U -r requirements.txt
  - pip install . --no-dependencies

script:
 - coverage run -m unittest discover
 - python -m doctest uniphy/*.py

after_success:
  - coveralls

deploy:
  provider: pypi
  user: phynix
  password:
    secure: "bgOx+gpsyEcuvfBGarU+AMlJJ1O0J639mxsTrVylnc4yw1o6ej0C5AE5QuMAxbTSG7OQ2eUL5S6Cfb+Q/RWXX7ep4D4Cr4tJz885tKL/B5Kf0mV6KBZcBSh0hxU2P3ykJ/Wp160SRU//tTMFFN1p0pGYa1OwoWulSMrYp2ggB94NFKwRcGAHjRDFB64K7yBZMq6TyYvd49adVVSlfgkfwdtXLaeGohPpNS38OJtJSmxGO//3wCCPjrucLW0Fd45TFXZLpfxSKN3EYC2gB22Uy4G0oVYaCZF6px2hcvTgPF0AMcbtcQU+rTf+4MNbO3ZmUJcnwBfh04vu5oI+Dss7spgaWtwjxFFVIw0DZFVPNWvyBz+anMrG97q28Rhpx7M4bqorSPZ8WIXi8MwplBUbu1gSyvok9scaQ2D/7Nte0KUlCdX+1n3o34sbN+Bx+HnMjVz2fxgP56f6PI4T8N0VIBl8slp6117DH4FBqxNpdbt18RJtKotF56BV8ukCPfoOyJaZmPhKZeLO0IJ14/CRcGLe8x+u45nSVjW5hPfDou/+6o+YoxlRQBeTKzpBzR5XG+OBdMGVIaz7FgOlN/JfqXlHGPLWhEpZrAbQ3NJ7AUGO28nq/PyPGj3z7uuijg5KDNP5YuSPZLKRFp7w3ebWhHbDRI68PB6mqHLr3L9h0Uo="
  distributions: sdist bdist_wheel
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6" && $TRAVIS_OS_NAME = "linux"
