os: linux
sudo: required
language: python
python:
 - '3.4'
 - '3.5'
 - '3.6'
 
matrix:
 include:
  - os: osx
  - language: generic
  
before_install:

# install anaconda

#install:

script:
 - echo "no tests"

